### ISSUE TITLE
where MailgunObject.php? 

### ISSUE THREAD

**Issue by supgeek-rod** [baibaratsky/php-mailgun#10]
include(MailgunObject.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory

**Comment by xpelliarmus** [comment]
MailgunOject interface is located in MailgunApi.php. I solved the issue by creating a new file MailgunObject.php and copying the MailgunOject interface to this file.

**Comment by baibaratsky** [comment]
@xpelliarmus, this topic is about another problem. Rod tried to include another library into his project, so he had no `MailgunApi.php` file. Please describe your issue in separate topic. There is no need to create `MailgunObject.php`.
