### ISSUE TITLE
Yii Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by git-no** [baibaratsky/php-mailgun#13]
Under Yii 1.1.17 this error 

```
php extends include(MailgunMessage.php): failed to open stream: No such file or directory
```

appears with 

```
$message = Yii::app()->mailgun->newMessage();
```

php-mailgun 1.2 Integrated into Yii extensions directory without composer.

It seems the MailgunYii.php does not find the MailgunMessage.php. 

Workaround was to add 

```
require(dirname(__FILE__).'/'.'MailgunMessage.php'); 
```

into MailgunYii.php.

**Comment by baibaratsky** [comment]
When not using composer, you have to load manually all files you need in your code. So this is not a bug. I recommend you not to modify the lib files, but put all `require()` expressions somewhere in your code.
