### ISSUE TITLE
Mailgun: How to keep track of the Message-ID (and References and In-Reply-To) to build threads

### ISSUE THREAD

**Issue by PrajapatiDhara1510** [baibaratsky/php-mailgun#15]
I want to keep thread when I reply to mail using Mailgun API.

Let me explain. I fetch mail using IMAP. I have message_id,subject,text,sender mail etc. Now I reply to that mail using Mailgun Yii extension. Here i face problem. I replied with same subject to that email-id but that person get mail as a new mail. Thread is not generated. In Php Mailer i find following way so thread is generated. But how to create thread using Mailgun Yii extension.

```
$mail->AddCustomHeader('In-Reply-To', $message_id);
$mail->addCustomHeader('References', $message_id);
```

**Comment by baibaratsky** [comment]
``` php
$message->addHeader('Your-Header', 'value');
```
